### ISSUE TITLE
Cannot download data by clicking the Export As, and TSV

### ISSUE THREAD

**Issue by beyondpie** [antigenomics/vdjdb-db#308] opened 2019-10-28 15:10 UTC
Hi, 
The database is so cool ! I want to download some data for research, but when I browse the data, and click the "Export As", then click "TSV", no responses...
Can you help me on this issue?
Thank you very much!
Songpeng

**Comment by mikessh** [comment] 2019-11-03 16:05
Dear Songpeng,

Thank you very much for reporting that This is actually an issue with vdjdb-web interface, so I re-reference it here: https://github.com/antigenomics/vdjdb-web/issues/62. I'm closing this issue, please monitor the issue at vdjdb-web.

It is not responding because the operation takes too much time on the entire database, presumably due to "paired records" flags. In the meantime, you can get the full version of the database from here: https://github.com/antigenomics/vdjdb-db/releases/latest (see https://github.com/antigenomics/vdjdb-db#database-build-contents for description of the release archive contents).

**Closed by mikessh** 2019-11-03 16:05 UTC

**Comment by beyondpie** [comment] 2019-11-03 16:07
Dear mikessh,
Thank you so much for your reply !  I will try that as soon as possible!
Songpeng

**Comment by bvdmitri** [comment] 2019-11-04 18:30
Dear @beyondpie,

Thank you for your feedback.
Indeed, there was a performance regression in our TSV export backend. 
We have reimplemented export's feature internal algorithm to make it more efficient and also added  a loading label. You can now try to export large datasets with the Web UI on https://vdjdb.cdr3.net/search.

**Comment by beyondpie** [comment] 2019-11-04 18:38
@mikessh @bvdmitri 
Thank you so much! I t works!
Songpeng
