### ISSUE TITLE
PMID:24069285

### ISSUE THREAD

**Issue by mikessh** [antigenomics/vdjdb-db#20] opened 2016-01-06 19:43 UTC
[Klinger M, Kong K, Moorhead M, Weng L, Zheng J, Faham M. Combining next-generation sequencing and immune assays: a novel method for identification of antigen-specific T cells. PLoS One. 2013 Sep 19;8(9):e74231. doi: 10.1371/journal.pone.0074231. eCollection 2013.](http://www.ncbi.nlm.nih.gov/pubmed/24069285)

**Comment by iziziz** [comment] 2016-05-31 17:45
assigned to me

**Comment by mikessh** [comment] 2016-06-24 21:30
V segments can be identified from sequence using http://www.ncbi.nlm.nih.gov/igblast/igblast.cgi  (TR tab, igblastp mode)

**Comment by iziziz** [comment] 2016-06-27 23:26
the authors haven't provided freq in acceptable format X/Y
they done it like this:
0.12% of Pentamer+ CD8 T cells
etc.

We have not to include the info (imho it's better option). Or we have to allow two formats in method.freq (bad option cause such way will not allow to assess overall count)

**Comment by mikessh** [comment] 2016-06-27 23:36
use 12/100 i think

**Comment by iziziz** [comment] 2016-06-29 08:34
I suppose allow format "x.xxx" for cases with amplicon-seq methodology

**Comment by iziziz** [comment] 2017-10-20 18:09
Misha, why the issue is opened? Seems, evrth is ok, doesn't it?

**Closed** 2017-10-20 18:18 UTC
Labels: formatting&proofreading, paper
